### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by iStooge** [PlanBCom/hubot-wit#1]
When I want to start Hubot I get the following error:

`ERROR Unable to load .../Hubot/node_modules/hubot-wit/src/hubot-wit: SyntaxError: Unexpected token {
  at exports.runInThisContext (vm.js:53:16)
  at Module._compile (module.js:373:25)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (.../Hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:300:12)
  at Module.require (module.js:353:17)
  at require (internal/module.js:12:17)
  at Robot.loadFile (.../Hubot/node_modules/hubot/src/robot.coffee:355:9, <js>:224:20)
  at module.exports (.../Hubot/node_modules/hubot-wit/index.coffee:11:9, <js>:24:31)
  at Robot.loadExternalScripts (.../Hubot/node_modules/hubot/src/robot.coffee:401:11, <js>:272:39)
  at .../Hubot/node_modules/hubot/bin/hubot:152:11, <js>:159:26
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)`

Could someone please fix this or help me?

**Comment by Godoy** [comment]
Hi!
Let me see your package.json, please.

**Comment by iStooge** [comment]
Hey!

This is my package.json:

`{
  "name": "bot",
  "version": "0.0.0",
  "private": true,
  "author": "iStooge",
  "description": "I'm a bot",
  "dependencies": {
    "htmlparser": "1.7.6",
    "hubot": "^2.19.0",
    "hubot-auth": "^2.0.0",
    "hubot-diagnostics": "0.0.1",
    "hubot-dynamic-conversation": "^1.0.1",
    "hubot-env": "0.0.2",
    "hubot-environment": "0.0.9",
    "hubot-google-images": "^0.2.6",
    "hubot-google-translate": "^0.2.0",
    "hubot-help": "^0.2.0",
    "hubot-heroku-keepalive": "^1.0.2",
    "hubot-ibmcloud-activity-emitter": "0.0.3",
    "hubot-ibmcloud-cloudant": "0.0.9",
    "hubot-ibmcloud-cognitive-entities": "0.0.8",
    "hubot-ibmcloud-cognitive-lib": "^0.1.5",
    "hubot-ibmcloud-translate": "0.0.25",
    "hubot-maps": "0.0.2",
    "hubot-mongodb-brain": "^0.1.1",
    "hubot-pugme": "^0.1.0",
    "hubot-recognizer": "^1.0.2",
    "hubot-redis-brain": "0.0.3",
    "hubot-reload-scripts": "^0.1.4",
    "hubot-rocketchat": "^1.0.4",
    "hubot-rules": "^0.1.1",
    "hubot-scripts": "^2.17.2",
    "hubot-shipit": "^0.2.0",
    "hubot-tweets": "0.0.1",
    "hubot-twitter-search": "^1.0.3",
    "hubot-wit-ai": "^0.1.4",
    "i18n-2": "^0.6.3",
    "mongodb": "^2.2.19",
    "pretty-ms": "^2.1.0",
    "soupselect": "0.2.0"
  },
  "devDependencies": {
    "hubot-ibmcloud-auth": ">=0.0.8",
    "hubot-ibmcloud-nlc": ">=0.0.20"
  },
  "engines": {
    "node": "0.10.x"
  }
}`

**Comment by iStooge** [comment]
Hey @Godoy 

Here is my package.json:

{
  "name": "bot",
  "version": "0.0.0",
  "private": true,
  "author": "iStooge",
  "description": "I'm a bot",
  "dependencies": {
    "htmlparser": "1.7.6",
    "hubot": "^2.19.0",
    "hubot-auth": "^2.0.0",
    "hubot-diagnostics": "0.0.1",
    "hubot-dynamic-conversation": "^1.0.1",
    "hubot-env": "0.0.2",
    "hubot-environment": "0.0.9",
    "hubot-google-images": "^0.2.6",
    "hubot-google-translate": "^0.2.0",
    "hubot-help": "^0.2.0",
    "hubot-heroku-keepalive": "^1.0.2",
    "hubot-ibmcloud-activity-emitter": "0.0.3",
    "hubot-ibmcloud-cloudant": "0.0.9",
    "hubot-ibmcloud-cognitive-entities": "0.0.8",
    "hubot-ibmcloud-cognitive-lib": "^0.1.5",
    "hubot-ibmcloud-translate": "0.0.25",
    "hubot-maps": "0.0.2",
    "hubot-mongodb-brain": "^0.1.1",
    "hubot-pugme": "^0.1.0",
    "hubot-recognizer": "^1.0.2",
    "hubot-redis-brain": "0.0.3",
    "hubot-reload-scripts": "^0.1.4",
    "hubot-rocketchat": "^1.0.4",
    "hubot-rules": "^0.1.1",
    "hubot-scripts": "^2.17.2",
    "hubot-shipit": "^0.2.0",
    "hubot-tweets": "0.0.1",
    "hubot-twitter-search": "^1.0.3",
    "hubot-wit": "^0.2.4",
    "i18n-2": "^0.6.3",
    "mongodb": "^2.2.19",
    "pretty-ms": "^2.1.0",
    "soupselect": "0.2.0"
  },
  "devDependencies": {
    "hubot-ibmcloud-auth": ">=0.0.8",
    "hubot-ibmcloud-nlc": ">=0.0.20"
  },
  "engines": {
    "node": "0.10.x"
  }
}

**Comment by Godoy** [comment]
I think the problem is in the interpretation of es6, already in the first line of package code: 
`const {Wit, log, interactive} = require('node-wit');`

Run `node -v` and tell me the node version please.  Versions prior to 6.0 needs some tricks
Related issues: 
http://stackoverflow.com/questions/39244008/unable-to-require-node-wit
http://stackoverflow.com/questions/17379277/destructuring-in-node-js

Maybe it works if you upgrade node or install babel.

**Comment by iStooge** [comment]
It seems to be my node version. I have v4.6.1 installed!

When I now want to do the trick with the --harmony_destructuring flag, how does this actually work in combination with hubot?

**Comment by Godoy** [comment]
I do not know either :sweat_smile:

Try edit `bin/hubot` in line 8 adding `--harmony_destructuring` :
```
exec node_modules/.bin/hubot --name "hubot-test" "$@" --harmony_destructuring
```

and run `bin/hubot`.

**Comment by iStooge** [comment]
Hmmm this seems not to work 😕
Just getting the following error after execution: `Unknown option: --harmony_destructuring`

**Comment by iStooge** [comment]
I just updated to the newest version of Node using NVM and it is working now! Thanks 😊
